Project NotificationApi {
        database_type: 'NotificationApiDB'
        Node: '''
                # Notification ERD
                **ERD elaborado para o banco de dados Firestore da NotificationApi**
        '''
}

Table subscribers {
       id              String      [not null, pk]
       user_id         String      [not null]
       value           String      [not null]
       segment         String      [not null]
       sign_up_date    Timestamp   [not null]
}

Table publishers_conn {
       id               String          [pk]
       subscriber_id    Reference       [not null, ref: > subscribers.id]
       publisher_id     String          [not null]

       Indexes {
          (subscriber_id, publisher_id) [name: 'UQ_publishers_conn_publisher_id_subscriber_id']
          publisher_id [unique]
          subscriber_id [unique]
       }
}

Table notifications {
       id              String           [not null, pk]
       publisher_id    Reference        [not null]
       title           String           [not null]
       message         String           [not null]
       created_at      Timestamp        [not null]
}

Table notifications_status {
        notification_id    Reference    [not null, ref: > notifications.id]
        subscriber_id      Reference    [not null, ref: > subscribers.id]
        accessed           boolean      [not null, default: false]
}
